NULL =

# Base and default-included sources and headers

WING_BASE_sources = \
	wingnamedpipeclient.c \
	wingnamedpipeconnection.c \
	wingnamedpipelistener.c \
	wingservice.c \
	wingservice-private.h \
	wingservicemanager.c \
	wingsource.c \
	wingutils.c \
	$(NULL)

WING_BASE_headers = \
	wing.h \
	wingversionmacros.h \
	wingnamedpipeclient.h \
	wingnamedpipeconnection.h \
	wingnamedpipelistener.h \
	wingservice.h \
	wingservicemanager.h \
	wingsource.h \
	wingutils.h \
	$(NULL)
